### ISSUE TITLE
How do I provide arguments to the binary?

### ISSUE THREAD

**Issue by MarkSwanson** [pegasos1/cargo-profiler#7]
I need to provide arguments to the binary or it won't work. How do I do that?

I tried using -- (like 'cargo run') but that didn't work:

RUST_BACKTRACE=1 cargo profiler cachegrind --bin ./test -- --arg1 a --arg2 b

Thanks.

**Comment by kernelmachine** [comment]
Ah, good catch, there isn't support for binary arguments right now. That would be a good thing to include. I imagine including the -- separator is the best way to do this to keep consistency with other subcommands.

**Comment by bnewbold** [comment]
I have submitted a pull request with a simple implementation for this, using the `--` syntax.

Because the binary name itself is not supplied as a "bare" positional argument (only to `--bin`), I thought it didn't make sense to try and use something like `AllowExternalSubcommands` from clap. This might be worth checking out in the future if it allowed example running syntax something like:
`cargo profiler callgrind some_example --example-arg`
instead of: 
`cargo profiler callgrind some_example -- --example-arg`

**Comment by MarkSwanson** [comment]
Thanks for working on this.
Edit: it seems to work fine. (I cloned your fork but forgot to checkout your binargs branch. Sorry for the noise.

**Comment by bnewbold** [comment]
Great!
(mostly posting this comment because I wasn't notified of your comment edit, and thus @pegasos1 probably wasn't either)

**Comment by kernelmachine** [comment]
This is merged in #23.
